In [1]:
from UTILITY_quickstart import *

#Load a the settings for a known-good lattice
#importedDefaultSettings = loadConfig("setLattice_configs/2024-10-22_oneBunch_baseline.yml")

#Initialize Bmad/Tao
tao = initializeTao()

Environment set to:  /Users/nmajik/Documents/SLAC/FACET2-Bmad-PyTao
Tracking to end
CSR off
Overwriting lattice with setLattice() defaults
No defaults file provided to setLattice(). Using setLattice_configs/defaults.yml
WARNING! No beam file is specified!
Number of macro particles defined by input file
Beam created, written to /Users/nmajik/Documents/SLAC/FACET2-Bmad-PyTao/beams/activeBeamFile.h5, and reinit to tao


In [2]:
getMatrix(tao, "ENDBC20", "DTOTR", print = True);

In [3]:
tao.taylor_map("ENDBC20", "DTOTR")

{1: {(0, 0, 0, 0, 0, 0): -1.92139546302812e-16,
  (1, 0, 0, 0, 0, 0): 1.38982500962486,
  (0, 1, 0, 0, 0, 0): -6.5591872620257,
  (0, 0, 1, 0, 0, 0): 1.64361356895922e-20,
  (0, 0, 0, 1, 0, 0): -8.76057393742784e-19,
  (0, 0, 0, 0, 0, 1): 5.5533472300419e-15},
 2: {(0, 0, 0, 0, 0, 0): -2.79559609023905e-17,
  (1, 0, 0, 0, 0, 0): 0.204433273419811,
  (0, 1, 0, 0, 0, 0): -0.245294278480053,
  (0, 0, 1, 0, 0, 0): 3.95742171043431e-20,
  (0, 0, 0, 1, 0, 0): -3.44903008487563e-19,
  (0, 0, 0, 0, 0, 1): 3.8900474054731e-16},
 3: {(0, 0, 0, 0, 0, 0): 5.70961898343852e-14,
  (1, 0, 0, 0, 0, 0): 1.38886057775417e-19,
  (0, 1, 0, 0, 0, 0): -1.08330487641452e-18,
  (0, 0, 1, 0, 0, 0): 0.705222422032069,
  (0, 0, 0, 1, 0, 0): -1.4109622990224,
  (0, 0, 0, 0, 0, 1): 0.0559202303725709},
 4: {(0, 0, 0, 0, 0, 0): 2.86229373536173e-17,
  (1, 0, 0, 0, 0, 0): 3.32013823261542e-20,
  (0, 1, 0, 0, 0, 0): -5.01620295146484e-20,
  (0, 0, 1, 0, 0, 0): -0.20323699037553,
  (0, 0, 0, 1, 0, 0): 1.82461545604138

In [4]:
tao.matrix(978.0, 990.0)

RuntimeError: Command: python matrix 978.0 990.0 causes error: ERROR detected: [ERROR | 2025-MAR-18 16:02:23] tao_python_cmd:
    "python matrix 978.0 990.0": Cannot locate element.
INVALID

In [5]:
?tao.matrix

Signature: tao.matrix(ele1_id, ele2_id, *, verbose=False, as_dict=True, raises=True)
Docstring:
Output matrix value from the exit end of one element to the exit end of the other.

Parameters
----------
ele1_id
ele2_id

Returns
-------
dict with keys:
    'mat6' : np.array of shape (6,6)
    'vec6' : np.array of shape(6)

Notes
-----
Command syntax:
  python matrix {ele1_id} {ele2_id}

Where:
  {ele1_id} is the start element.
  {ele2_id} is the end element.
If {ele2_id} = {ele1_id}, the 1-turn transfer map is computed.
Note: {ele2_id} should just be an element name or index without universe, branch, or model/base/design specification.

Example:
  python matrix 2@1>>q01w|design q02w

Examples
--------
Example: 1
 init: -init $ACC_ROOT_DIR/regression_tests/python_test/cesr/tao.init
 args:
   ele1_id: 1@0>>q01w|design
   ele2_id: q02w
File:      /opt/homebrew/anaconda3/envs/bmad/lib/python3.11/site-packages/pytao/interface_commands.py
Type:      method

In [6]:
?tao.taylor_map

Signature:
tao.taylor_map(
    ele1_id,
    ele2_id,
    *,
    order='1',
    verbose=False,
    as_dict=True,
    raises=True,
)
Docstring:
Output Taylor map between two points.

Parameters
----------
ele1_id
ele2_id
order : default=1

Returns
-------
dict of dict of taylor terms:
    {2: { (3,0,0,0,0,0)}: 4.56, ... 
        corresponding to: px_out = 4.56 * x_in^3

Notes
-----
Command syntax:
  python taylor_map {ele1_id} {ele2_id} {order}

Where:
  {ele1_id} is the start element.
  {ele2_id} is the end element.
  {order} is the map order. Default is order set in the lattice file. {order} cannot be larger than 
        what is set by the lattice file. 
If {ele2_id} = {ele1_id}, the 1-turn transfer map is computed.
Note: {ele2_id} should just be an element name or index without universe, branch, or model/base/design specification.
Example:
  python taylor_map 2@1>>q01w|design q02w  2

Examples
--------
Example: 1
 init: -init $ACC_ROOT_DIR/regression_tests/python_test/cesr/tao.init
 

In [7]:
tao.taylor_map("ENDBC20->1.0", "DTOTR")

RuntimeError: Command: python taylor_map ENDBC20->1.0 DTOTR 1 causes error: ERROR detected: [ERROR | 2025-MAR-18 16:02:46] lat_ele1_locator:
    INVALID OFFSET SYNTAX: ENDBC20->1.0
[ERROR | 2025-MAR-18 16:02:46] tao_python_cmd:
    "python taylor_map ENDBC20->1.0 DTOTR 1": Cannot locate element.
INVALID

In [8]:
?tao

Type:        Tao
String form: <pytao.tao_ctypes.core.Tao object at 0x162f58d90>
File:        /opt/homebrew/anaconda3/envs/bmad/lib/python3.11/site-packages/pytao/tao_ctypes/core.py
Docstring:  
Class to run and interact with Tao. Requires libtao shared object.

Setup:

import os
import sys
TAO_PYTHON_DIR=os.environ['ACC_ROOT_DIR'] + '/tao/python'
sys.path.insert(0, TAO_PYTHON_DIR)

import tao_ctypes
tao = tao_ctypes.Tao()
tao.init("command line args here...")

In [9]:
tao.show("taylor_map -s 970 990 -order 0")

['  -0.000000  -0.000000  -0.000000   0.000000   0.000000   0.000000']

In [10]:
tao.show("taylor_map -s 970 990")

['Symplectic Error:  2.00E-15',
 '',
 '    -4.37416457     1.79482674     0.00000000     0.00000000     0.00000000     0.12462135   :  1.18987863E-14',
 '     2.05570926    -1.07212289    -0.00000000    -0.00000000     0.00000000    -0.04993251   :  6.51142677E-16',
 '     0.00000000    -0.00000000    -2.53193352    -5.67447504     0.00000000    -0.00000000   :  3.28971416E-16',
 '     0.00000000    -0.00000000    -0.76515299    -2.10978744     0.00000000     0.00000000   : -1.79941085E-17',
 '     0.03777227    -0.04398921     0.00000000     0.00000000     1.00000000    -0.00008669   :  7.53627598E-17',
 '     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000     1.00000000   :  0.00000000E+00']

In [11]:
getMatrix(tao, "BEGBC20", "DTOTR")

array([[-1.06110711e+00,  1.48946410e+00, -8.99713280e-17,
        -6.88724435e-16,  0.00000000e+00,  7.35459263e-04],
       [-2.20260570e-01, -6.33234646e-01, -6.19801723e-18,
        -4.84438559e-17,  0.00000000e+00,  1.25921582e-04],
       [-4.79293313e-17, -2.89188220e-16, -2.78571167e-01,
         5.79812255e+00,  0.00000000e+00,  5.59202304e-02],
       [ 1.33807186e-17,  7.86458748e-17, -5.24991902e-02,
        -2.49703970e+00,  0.00000000e+00,  6.00001800e-03],
       [-2.83763896e-05, -6.53273963e-04, -1.26433480e-03,
        -1.74423875e-01,  1.00000000e+00, -7.04666453e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
lines = tao.show("taylor_map BEGBC20 DTOTR")

def parse_symplectic_output(lines):
    data = []

    for line in lines:
        if ':' in line:
            values, _ = line.rsplit(':', 1)  # Split at colon, keeping only the left part
            row = [float(v) for v in values.split() if v]  # Convert values to float, ignoring empty strings
            data.append(row)

    return np.array(data, dtype=np.float64)

parse_symplectic_output(lines)

ValueError: could not convert string to float: 'Symplectic'

In [13]:
def newTaoFunction(tao, ele1_id, ele2_id, *, order='1', verbose=False):
    cmd = f'python taylor_map {ele1_id} {ele2_id} {order}'
    if verbose:
        print(cmd)
    return tao.cmd(cmd)  # Execute the command

# Example usage:
result = newTaoFunction(tao, "BEGBC20", "DTOTR")
result


['1;term; -1.46781052035278E-15;0;0;0;0;0;0',
 '1;term; -1.06110711309025E+00;1;0;0;0;0;0',
 '1;term;  1.48946410497703E+00;0;1;0;0;0;0',
 '1;term; -3.92569696964463E-16;0;0;1;0;0;0',
 '1;term;  1.97258130449636E-15;0;0;0;1;0;0',
 '1;term;  7.35459262935597E-04;0;0;0;0;0;1',
 '2;term; -5.48917888989078E-17;0;0;0;0;0;0',
 '2;term; -2.20260569940658E-01;1;0;0;0;0;0',
 '2;term; -6.33234646193940E-01;0;1;0;0;0;0',
 '2;term; -7.96159696918683E-17;0;0;1;0;0;0',
 '2;term;  3.38160937854161E-17;0;0;0;1;0;0',
 '2;term;  1.25921582494534E-04;0;0;0;0;0;1',
 '3;term; -7.35952406551569E-14;0;0;0;0;0;0',
 '3;term; -4.37623440635323E-17;1;0;0;0;0;0',
 '3;term; -1.16570058427018E-15;0;1;0;0;0;0',
 '3;term; -2.78571166654524E-01;0;0;1;0;0;0',
 '3;term;  5.79812254766726E+00;0;0;0;1;0;0',
 '3;term;  5.59202303728775E-02;0;0;0;0;0;1',
 '4;term; -1.89692012098064E-15;0;0;0;0;0;0',
 '4;term;  4.92323250069276E-17;1;0;0;0;0;0',
 '4;term;  8.96980713582604E-16;0;1;0;0;0;0',
 '4;term; -5.24991902484566E-02;0;

In [14]:
def newTaoFunction(tao, ele1_s, ele2_s, *, order='1', verbose=False):
    cmd = f'python taylor_map -s {ele1_s} {ele2_s} {order}'
    if verbose:
        print(cmd)
    return tao.cmd(cmd)  # Execute the command

# Example usage:
result = newTaoFunction(tao, 780, 790)
result

RuntimeError: Command: python taylor_map -s 780 790 1 causes error: ERROR detected: [ERROR | 2025-MAR-18 16:02:49] lat_ele1_locator:
    INVALID OFFSET SYNTAX: -S
[ERROR | 2025-MAR-18 16:02:49] tao_python_cmd:
    "python taylor_map -s 780 790 1": Cannot locate element.
INVALID

In [26]:
allStrings = tao.show("taylor_map -s 970 990")
splitStrings = [str.split() for str in allStrings]
splitStrings

[['Symplectic', 'Error:', '1.44E-15'],
 [],
 ['-4.37416279',
  '1.79482584',
  '0.00000000',
  '0.00000000',
  '0.00000000',
  '0.12462130',
  ':',
  '-8.15820441E-14'],
 ['2.05570936',
  '-1.07212294',
  '-0.00000000',
  '-0.00000000',
  '0.00000000',
  '-0.04993251',
  ':',
  '-4.49373075E-15'],
 ['0.00000000',
  '-0.00000000',
  '-2.53193421',
  '-5.67447691',
  '0.00000000',
  '0.00000000',
  ':',
  '6.43600710E-15'],
 ['0.00000000',
  '-0.00000000',
  '-0.76515295',
  '-2.10978734',
  '0.00000000',
  '-0.00000000',
  ':',
  '-3.53252822E-16'],
 ['0.03777224',
  '-0.04398920',
  '-0.00000000',
  '-0.00000000',
  '1.00000000',
  '-0.00008669',
  ':',
  '9.95570039E-16'],
 ['0.00000000',
  '0.00000000',
  '0.00000000',
  '0.00000000',
  '0.00000000',
  '1.00000000',
  ':',
  '0.00000000E+00']]

In [29]:
np.array([ [float(str) for str in row[0:6]] for row in splitStrings[2:] ])

array([[-4.37416279e+00,  1.79482584e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.24621300e-01],
       [ 2.05570936e+00, -1.07212294e+00, -0.00000000e+00,
        -0.00000000e+00,  0.00000000e+00, -4.99325100e-02],
       [ 0.00000000e+00, -0.00000000e+00, -2.53193421e+00,
        -5.67447691e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -0.00000000e+00, -7.65152950e-01,
        -2.10978734e+00,  0.00000000e+00, -0.00000000e+00],
       [ 3.77722400e-02, -4.39892000e-02, -0.00000000e+00,
        -0.00000000e+00,  1.00000000e+00, -8.66900000e-05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [45]:
getMatrix(tao, "MFFF", "DTOTR")

array([[ 1.38982501e+00, -7.09263129e+00,  4.52367703e-19,
        -4.13820977e-18,  0.00000000e+00,  5.52724582e-15],
       [ 2.04433273e-01, -3.23760062e-01,  3.95667129e-20,
        -3.60036377e-19,  0.00000000e+00,  3.89112428e-16],
       [-1.80683299e-19, -6.30380087e-19,  7.05222422e-01,
        -1.68164147e+00,  0.00000000e+00,  5.59202304e-02],
       [-1.08713683e-21, -8.58872114e-21, -2.03236990e-01,
         1.90262208e+00,  0.00000000e+00,  6.00001800e-03],
       [ 5.89155795e-16,  9.70332836e-16, -1.55964065e-02,
         1.16484944e-01,  1.00000000e+00, -5.77033179e-06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [51]:
getMatrix(tao, "MFFF", "DTOTR", order = 0)

array([-3.29376264e-29, -2.31011918e-30, -1.22598493e-18, -1.23021496e-19,
       -3.05299474e-17,  0.00000000e+00])

In [53]:
allStrings = tao.show("taylor_map -order 0 -s 970 990")
np.array([float(str) for str in allStrings[0].split()])

array([-0., -0., -0.,  0.,  0.,  0.])

In [57]:
def getMatrixNew(tao, start, end, order = 1, startOffset = 0, endOffset = 0, print = False):
    """Return zero or first order transport matrix from start to end, with offsets. Optionally print in a human readable format"""
    
    startS = tao.ele_head(start)["s"] + startOffset
    endS = tao.ele_head(end)["s"] + endOffset

    #This disgusting workaround is required because PyTao implementation of taylor_map doesn't support -s mode
    if order == 0: 
        allStrings = tao.show(f"taylor_map -order 0 -s {startS} {endS}")
        transportMatrix = np.array([float(str) for str in allStrings[0].split()])
    
    
    elif order == 1:
        allStrings = tao.show(f"taylor_map -s {startS} {endS}")
        splitStrings = [str.split() for str in allStrings]
        transportMatrix = np.array([ [float(str) for str in row[0:6]] for row in splitStrings[2:] ])
    
    
    else:
        print("Invalid matrix order requested")
        return
    


    if print:
        displayMatrix(transportMatrix)
        
    return transportMatrix


getMatrix(tao, "BEGBC20", "MFFF", print = True);
getMatrixNew(tao, "BEGBC20", "MFFF", print = True);

In [44]:
getMatrixNew(tao, "BEGBC20", "MFFF", startOffset = -1, endOffset = 1, print = True);

In [58]:
getMatrixNew(tao, "BEGBC20", "MFFF", startOffset = -1, endOffset = 1, order = 0, print = True);